# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kihara Ri
subtitle: 'No day can be the same'
description: 'æˆ‘è¿˜æ²¡æƒ³å¥½ğŸ˜³'
keywords: 'tech,æŠ˜è…¾å…š,ç†å·¥'
author: Kihara Ri
language: zh-CN
timezone:

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://limuyuan.top
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: false # butterfly ä¸»é¢˜éœ€è¦æ”¹ç”¨äºæ¢è¡Œ
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:Kihara-Ri/Kihara-Ri.github.io.git
  branch: main

abbrlink:
  alg: crc32
  rep: hex

search:
  path: search.xml
  field: all
  content: true

# è¿½ç•ªæ’ä»¶
# https://github.com/HCLonely/hexo-bilibili-bangumi
bangumi: # è¿½ç•ªè®¾ç½®
  enable: true
  source: bili
  # bgmInfoSource: 'bgmApi'
  path:
  vmid: 631081975        # 740765 # bç«™æˆ–bangumi id
  title: "æˆ‘çœ‹çš„åŠ¨ç”»/ç•ªå‰§"
  quote: "æ—¥æœ¬åŠ¨ç”»å°±æ˜¯æœ‰è¿™æ ·ä¸€ç§é­…åŠ›ï¼Œå®ƒä¸è¯´æ•™å¼åœ°å‘Šè¯‰æˆ‘ä»¬äººç”Ÿåº”å½“æ˜¯æ€æ ·çš„ï¼Œè€Œæ˜¯é€šè¿‡åˆ«äººçš„äººç”Ÿå¼•å¯¼æˆ‘ä»¬<br>â€”â€”ä½ æƒ³æ´»å‡ºæ€æ ·çš„äººç”Ÿï¼Ÿ<br>ğŸ­ğŸ­è™½ç„¶å·²ç»è¿‡äº†ä¸­äºŒçš„å¹´é¾„ï¼Œçƒ­è¡€çš„ã€å°‘å¹´çš„ã€ç‹é“çš„ã€æ‰“æ–—çš„éƒ½ä¸æ„Ÿå…´è¶£ï¼Œä½†æ˜¯å¯¹äººçš„æ¢ç´¢ï¼Œå´æ˜¯æ¯ä¸ªäººæ°¸æ’çš„è¯é¢˜"
  show: 1
  # lazyload: true
  # loading: '__image__'
  # lazyloadAttrName: 'data-src=__image__'
  # showMyComment: true
  # pagination: true
  metaColor: '#9d65c2'  # ç®€ä»‹ä¸Šæ–¹å­—ä½“é¢œè‰²
  color:  # ç®€ä»‹å­—ä½“é¢œè‰²
  webp:
  progress: true
  order: latest # latest | score | -score
  extraOrder:
  proxy:
    host: "ä»£ç†host"
    port: "ä»£ç†ç«¯å£"
  extra_options:
    key: 

# APlayer
# https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer:
  # script_dir: some/place                        # Public ç›®å½•ä¸‹è„šæœ¬ç›®å½•è·¯å¾„ï¼Œé»˜è®¤: 'assets/js'
  # style_dir: some/place                         # Public ç›®å½•ä¸‹æ ·å¼ç›®å½•è·¯å¾„ï¼Œé»˜è®¤: 'assets/css'
  # cdn: http://xxx/aplayer.min.js                # å¼•ç”¨ APlayer.js å¤–éƒ¨ CDN åœ°å€ (é»˜è®¤ä¸å¼€å¯)
  # style_cdn: http://xxx/aplayer.min.css         # å¼•ç”¨ APlayer.css å¤–éƒ¨ CDN åœ°å€ (é»˜è®¤ä¸å¼€å¯)
  meting: true                                  # MetingJS æ”¯æŒ
  # meting_api: http://xxx/api.php                # è‡ªå®šä¹‰ Meting API åœ°å€
  # meting_cdn: http://xxx/Meing.min.js           # å¼•ç”¨ Meting.js å¤–éƒ¨ CDN åœ°å€ (é»˜è®¤ä¸å¼€å¯)
  asset_inject: true                            # è‡ªåŠ¨æ’å…¥ Aplayer.js ä¸ Meting.js èµ„æºè„šæœ¬, é»˜è®¤å¼€å¯
  # externalLink: http://xxx/aplayer.min.js       # è€ç‰ˆæœ¬å‚æ•°ï¼ŒåŠŸèƒ½ä¸å‚æ•° cdn ç›¸åŒ

pandoc:
  args:
    - '-f'
    - 'commonmark_x'
    - '-t'
    - 'html'
    - '--mathjax'
  extensions:
    - '-implicit_figures'

mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: true # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
  packages:
    - physics
    - mathtools
    - color
    - noerrors
    - amsmath
  extension_options: {}
    # you can put your extension options here
    # see http://docs.mathjax.org/en/latest/options/input/tex.html#tex-extension-options for more detail


douban:
  id: 251545335
  builtin: false
  item_per_page: 10
  meta_max_line: 4
  customize_layout: page
  book:
    path: books/index.html
    title: 'è¯»ä¹¦æ¸…å•'
    quote: 'å› ä¸ºæœ¬äººæ˜¯ç†å·¥ç§‘å°¤å…¶æ˜¯ç¼–ç¨‹ç‹‚çƒ­çˆ±å¥½è€…ï¼Œå› æ­¤è¯»çš„ä¹¦ä¸­æŠ€æœ¯ç›¸å…³çš„ä¼šæ¯”è¾ƒå¤š<br>å…¶ä»–ä¹¦ä¹Ÿä¼šè¯»ï¼Œä½†æ˜¯æ›´åå‘äºå†å²ã€ç»æµç¤¾ç§‘ç­‰çœŸå®å†…å®¹'
    option:
  movie:
    path: movies/index.html
    title: 'çœ‹è¿‡çš„ç”µå½±'
    quote: 'æœ¬äººè™½ç„¶æ²¡æœ‰ä»€ä¹ˆè‰ºæœ¯é€ è¯£å’Œå®¡ç¾èƒ½åŠ›ï¼Œä½†æ˜¯æ ¹æ®æˆ‘å¯¹ç¤¾ç§‘æµ…æ˜¾çš„è®¤è¯†ï¼Œæˆ‘æ›´å–œæ¬¢é‚£äº›æœ‰è®½åˆºæ„å‘³å’Œæœ‰æ·±åº¦æ€è€ƒç©ºé—´çš„ç”µå½±ä½œå“'
    option:
  # game:
  #   path: games/index.html
  #   title: 'This is my game title'
  #   quote: 'This is my game quote'
  #   option:
  # song:
  #   path: songs/index.html
  #   title: 'This is my song title'
  #   quote: 'This is my song quote'
  #   option:
  timeout: 10000 